export const MOVIES_LOADED = 'MOVIES_LOADED';
export const START_MOVIES_LOADIND = 'START_MOVIES_LOADIND';
export const ERROR_LOADIND_MOVIES = 'ERROR_LOADIND_MOVIES';
export const STOP_MOVIES_LOADIND = 'STOP_MOVIES_LOADIND';